base_model: meta-llama/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

chat_template: chatml
datasets:
  - path: ./datasets/ablation_all_properties.jsonl
    type: alpaca:chatml

dataset_prepared_path: ./work_dir/llama3_last_run_prepared
val_set_size: 0.1
output_dir: ./work_dir/models/llama3-abl1-lora-out

sequence_len: 4000
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: true

adapter: qlora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save:
 - embed_tokens
 - lm_head

wandb_project: clsit-v2
wandb_entity:
wandb_watch:
wandb_name: llama3-8b-abl1
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.00015

train_on_inputs: false
group_by_length: false
bf16: true
fp16:
tf32: false

gradient_checkpointing: unsloth
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: 
s2_attention:

# warmup_steps: 10
warmup_ratio: 0.5
evals_per_epoch: 1
eval_table_size: 128
eval_table_max_new_tokens: 256
saves_per_epoch: 1
save_total_limit: 2
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
seed: 42
special_tokens:
   pad_token: <|end_of_text|>

tokens: # these are delimiters
  - "<|im_start|>"
  - "<|im_end|>"